package com.mathapp.practice.ui

enum class AppLanguage(val code: String, val displayName: String) {
    KOREAN("ko", "한국어"),
    ENGLISH("en", "English"),
    CHINESE_TRADITIONAL("zh-Hant", "中文(繁體)"),
    CHINESE_SIMPLIFIED("zh-Hans", "中文(简体)"),
    JAPANESE("ja", "日本語");

    companion object {
        fun fromCode(code: String): AppLanguage = entries.find { it.code == code } ?: ENGLISH
    }
}

object L10n {
    private val strings = mapOf(
        AppLanguage.KOREAN to mapOf(
            "reset_records" to "기록 초기화",
            "start" to "시작",
            "best_record" to "최고 기록",
            "time_format" to "%.2f초",
            "light" to "라이트",
            "dark" to "다크",
            "reset_confirm_title" to "기록을 초기화하시겠습니까?",
            "reset" to "초기화",
            "cancel" to "취소",
            "reset_confirm_message" to "최고 기록이 삭제됩니다.",
            "countdown_go" to "시작!",
            "complete" to "완료!",
            "new_record_title" to "최고 기록을 경신했어요! 🎉",
            "new_record_message" to "10문제를 모두 풀고\n새로운 기록을 세웠어요. 축하해요!",
            "well_done" to "수고하셨습니다",
            "best_record_format" to "최고 기록 %s",
            "to_main" to "메인으로",
            "quit_confirm" to "그만하시겠습니까?",
            "no" to "아니오",
            "yes" to "예",
            "confirm" to "확인",
            "language" to "언어",
            "level_easy" to "쉬움",
            "level_normal" to "보통",
            "help_title" to "레벨 설명",
            "help_easy_desc" to "• 왼쪽 숫자: 0~99\n• 오른쪽 숫자: 0~10\n• 뺄셈 시 결과가 음수가 되지 않음",
            "help_normal_desc" to "• 왼쪽 숫자: 0~99\n• 오른쪽 숫자: 0~99\n• 덧셈과 뺄셈 (음수 가능)",
            // ── New strings for stage UX ──
            "resume" to "이어서 하기",
            "new_start" to "새로 시작하기",
            "select_operation" to "연산 선택",
            "overall_progress" to "전체 진척도",
            "locked" to "잠김",
            "stage_map_title" to "스테이지 선택",
            "reset_progress" to "진척도 초기화",
            "reset_progress_confirm_title" to "진척도를 초기화하시겠습니까?",
            "reset_progress_confirm_message" to "모든 스테이지 기록이 삭제됩니다.",
            "stage_num_format" to "%d단계",
            "resume_hint" to "%s %d단계",
            "problem_progress" to "%d / 10",
            "result_title_3star" to "완벽해요!",
            "result_title_2star" to "잘했어요!",
            "result_title_1star" to "완주했어요!",
            "correct_format" to "맞힌 문제: %d / 10",
            "avg_time_format" to "평균 %.1f초",
            "avg_label" to "평균",
            "retry" to "다시 하기",
            "next_stage" to "다음 단계로",
            "to_stage_map" to "스테이지 맵으로",
            "star_cond_3" to "⭐⭐⭐  만점 + 평균 6초 이하",
            "star_cond_2" to "⭐⭐  8문제 이상 정답",
            "star_cond_1" to "⭐  완주 성공",
            "points_earned" to "%d P 획득!",
            "hearts_display" to "❤️ %d / %d",
            "next_heart_timer" to "+1 %02d:%02d",
            "total_points_format" to "누적 %d P",
            // ── Onboarding & Character ──
            "onboarding_title" to "수학 모험을 시작해요!",
            "onboarding_desc" to "재미있는 문제를 풀면서\n별을 모아보아요!",
            "onboarding_start" to "🚀 모험 시작하기",
            "select_character" to "내 친구를 선택해요",
            "character_confirm" to "친구와 함께하기 🎉",
            "char_bear" to "곰돌이",
            "char_rabbit" to "토끼",
            "char_fox" to "여우",
            "char_owl" to "부엉이",
            // ── Daily Quest ──
            "quest_title" to "오늘의 퀘스트",
            "quest_continue" to "계속하기 🚀",
            "quest_completed_title" to "오늘의 퀘스트 완료!",
            "quest_completed_sub" to "대단해요! 오늘도 수학을 열심히 했어요",
            "quest_desc_progress" to "%s %d단계 도전",
            "quest_desc_review" to "%s %d단계 복습",
            "quest_desc_new" to "%s 처음 시작",
            "quest_problems" to "%d문제",
            // ── Bottom Nav ──
            "nav_home" to "홈",
            "nav_report" to "진행상황",
            "nav_treasure" to "보물 상자",
            // ── Learning Report ──
            "report_title" to "학습 리포트",
            "report_solved" to "완료한 문제",
            "report_accuracy" to "정확도",
            "report_streak" to "연속 학습",
            "report_streak_unit" to "일",
            "report_weekly" to "주간 학습 기록",
            "report_badges" to "획득한 배지",
            "report_day_mon" to "월",
            "report_day_tue" to "화",
            "report_day_wed" to "수",
            "report_day_thu" to "목",
            "report_day_fri" to "금",
            "report_day_sat" to "토",
            "report_day_sun" to "일",
            // ── Badges ──
            "badge_first_step" to "첫 걸음",
            "badge_first_step_desc" to "첫 스테이지 클리어",
            "badge_speed_demon" to "번개 같은 손",
            "badge_speed_demon_desc" to "별 3개 획득",
            "badge_perfectionist" to "완벽주의자",
            "badge_perfectionist_desc" to "별 3개 10회 달성",
            "badge_math_master" to "수학 달인",
            "badge_math_master_desc" to "모든 스테이지 클리어",
            "badge_consistent" to "꾸준함",
            "badge_consistent_desc" to "7일 연속 학습",
            "badge_explorer" to "탐험가",
            "badge_explorer_desc" to "모든 연산 도전",
            // ── Parent Settings ──
            "parent_settings_title" to "설정",
            "parent_notifications" to "알림 설정",
            "parent_study_notification" to "학습 알림",
            "parent_achievement_notification" to "성과 알림",
            "parent_study_management" to "학습 관리",
            "parent_time_limit" to "시간 제한",
            "parent_daily_goal" to "일일 학습 목표 (분)",
            "parent_display" to "화면",
            "parent_data" to "데이터",
            "parent_account" to "계정",
            "parent_logout" to "로그아웃",
            // ── Treasure Chest ──
            "treasure_title" to "보물 상자",
            "treasure_level" to "레벨",
            "treasure_level_progress" to "다음 레벨까지",
            "treasure_collection" to "보물 컬렉션",
            "treasure_locked" to "잠김",
            "stage_confirm_title" to "스테이지 시작",
            "stage_confirm_message" to "%s을(를) 시작하시겠습니까?",
            "stage_start" to "시작하기",
            "multiple_choice" to "객관식",
            "fill_in" to "주관식",
            "to_home" to "메인으로",
            // ── Shop ──
            "shop_title" to "상점",
            "shop_coins" to "🪙 %d 코인",
            "shop_tab_accessory" to "꾸미기",
            "shop_tab_effect" to "효과",
            "shop_tab_deco" to "장식",
            "shop_buy" to "구매",
            "shop_owned" to "보유 중",
            "shop_equip" to "장착",
            "shop_equipped" to "장착 중",
            "shop_not_enough" to "코인 부족",
            "item_crown" to "왕관",
            "item_hat" to "모자",
            "item_glasses" to "안경",
            "item_ribbon" to "리본",
            "item_star" to "별 장식",
            "item_party" to "파티 효과",
            "item_sparkle" to "반짝임",
            "item_balloon" to "풍선",
            "item_rainbow" to "무지개",
            "item_flowers" to "꽃 장식",
            "item_castle" to "성"
        ),
        AppLanguage.ENGLISH to mapOf(
            "reset_records" to "Reset Records",
            "start" to "Start",
            "best_record" to "Best Record",
            "time_format" to "%.2fs",
            "light" to "Light",
            "dark" to "Dark",
            "reset_confirm_title" to "Reset your best record?",
            "reset" to "Reset",
            "cancel" to "Cancel",
            "reset_confirm_message" to "Your best record will be deleted.",
            "countdown_go" to "Go!",
            "complete" to "Complete!",
            "new_record_title" to "New Record! 🎉",
            "new_record_message" to "You solved all 10 problems\nand set a new record. Congratulations!",
            "well_done" to "Well done!",
            "best_record_format" to "Best record %s",
            "to_main" to "To Main",
            "quit_confirm" to "Quit the game?",
            "no" to "No",
            "yes" to "Yes",
            "confirm" to "Confirm",
            "language" to "Language",
            "level_easy" to "Easy",
            "level_normal" to "Normal",
            "help_title" to "Level Guide",
            "help_easy_desc" to "• Left number: 0~99\n• Right number: 0~10\n• Subtraction: result is never negative",
            "help_normal_desc" to "• Left number: 0~99\n• Right number: 0~99\n• Addition and subtraction (negative allowed)",
            // ── New strings for stage UX ──
            "resume" to "Continue",
            "new_start" to "Choose Operation",
            "select_operation" to "Select Operation",
            "overall_progress" to "Overall Progress",
            "locked" to "Locked",
            "stage_map_title" to "Select Stage",
            "reset_progress" to "Reset Progress",
            "reset_progress_confirm_title" to "Reset all progress?",
            "reset_progress_confirm_message" to "All stage records will be deleted.",
            "stage_num_format" to "Stage %d",
            "resume_hint" to "%s Stage %d",
            "problem_progress" to "%d / 10",
            "result_title_3star" to "Perfect!",
            "result_title_2star" to "Great job!",
            "result_title_1star" to "You did it!",
            "correct_format" to "Correct: %d / 10",
            "avg_time_format" to "Avg %.1fs",
            "avg_label" to "Avg",
            "retry" to "Try Again",
            "next_stage" to "Next Stage",
            "to_stage_map" to "Stage Map",
            "star_cond_3" to "⭐⭐⭐  Perfect score + avg ≤ 6s",
            "star_cond_2" to "⭐⭐  8 or more correct",
            "star_cond_1" to "⭐  Finish all 10",
            "points_earned" to "%d P earned!",
            "hearts_display" to "❤️ %d / %d",
            "next_heart_timer" to "+1 %02d:%02d",
            "total_points_format" to "Total %d P",
            // ── Onboarding & Character ──
            "onboarding_title" to "Start Your Math Adventure!",
            "onboarding_desc" to "Solve fun problems and\ncollect stars!",
            "onboarding_start" to "🚀 Start Adventure",
            "select_character" to "Choose Your Friend",
            "character_confirm" to "Let's Go Together! 🎉",
            "char_bear" to "Bear",
            "char_rabbit" to "Rabbit",
            "char_fox" to "Fox",
            "char_owl" to "Owl",
            // ── Daily Quest ──
            "quest_title" to "Today's Quest",
            "quest_continue" to "Continue 🚀",
            "quest_completed_title" to "Quest Complete!",
            "quest_completed_sub" to "Amazing! Keep up the great work!",
            "quest_desc_progress" to "%s Stage %d Challenge",
            "quest_desc_review" to "%s Stage %d Review",
            "quest_desc_new" to "%s First Steps",
            "quest_problems" to "%d problems",
            // ── Bottom Nav ──
            "nav_home" to "Home",
            "nav_report" to "Progress",
            "nav_treasure" to "Treasure",
            // ── Learning Report ──
            "report_title" to "Learning Report",
            "report_solved" to "Problems Done",
            "report_accuracy" to "Accuracy",
            "report_streak" to "Streak",
            "report_streak_unit" to " days",
            "report_weekly" to "Weekly Activity",
            "report_badges" to "Badges",
            "report_day_mon" to "Mon",
            "report_day_tue" to "Tue",
            "report_day_wed" to "Wed",
            "report_day_thu" to "Thu",
            "report_day_fri" to "Fri",
            "report_day_sat" to "Sat",
            "report_day_sun" to "Sun",
            // ── Badges ──
            "badge_first_step" to "First Step",
            "badge_first_step_desc" to "Clear your first stage",
            "badge_speed_demon" to "Speed Demon",
            "badge_speed_demon_desc" to "Earn 3 stars on a stage",
            "badge_perfectionist" to "Perfectionist",
            "badge_perfectionist_desc" to "Get 3 stars 10 times",
            "badge_math_master" to "Math Master",
            "badge_math_master_desc" to "Clear all 40 stages",
            "badge_consistent" to "Consistent",
            "badge_consistent_desc" to "Play 7 days in a row",
            "badge_explorer" to "Explorer",
            "badge_explorer_desc" to "Try all operations",
            // ── Parent Settings ──
            "parent_settings_title" to "Settings",
            "parent_notifications" to "Notifications",
            "parent_study_notification" to "Study Reminders",
            "parent_achievement_notification" to "Achievement Alerts",
            "parent_study_management" to "Study Management",
            "parent_time_limit" to "Time Limit",
            "parent_daily_goal" to "Daily Goal (minutes)",
            "parent_display" to "Display",
            "parent_data" to "Data",
            "parent_account" to "Account",
            "parent_logout" to "Log Out",
            // ── Treasure Chest ──
            "treasure_title" to "Treasure Chest",
            "treasure_level" to "Level",
            "treasure_level_progress" to "To next level",
            "treasure_collection" to "Collection",
            "treasure_locked" to "Locked",
            "stage_confirm_title" to "Start Stage",
            "stage_confirm_message" to "Start %s?",
            "stage_start" to "Start",
            "multiple_choice" to "Multiple Choice",
            "fill_in" to "Fill In",
            "to_home" to "Home",
            // ── Shop ──
            "shop_title" to "Shop",
            "shop_coins" to "🪙 %d coins",
            "shop_tab_accessory" to "Outfit",
            "shop_tab_effect" to "Effects",
            "shop_tab_deco" to "Decor",
            "shop_buy" to "Buy",
            "shop_owned" to "Owned",
            "shop_equip" to "Equip",
            "shop_equipped" to "Equipped",
            "shop_not_enough" to "Not enough",
            "item_crown" to "Crown",
            "item_hat" to "Hat",
            "item_glasses" to "Glasses",
            "item_ribbon" to "Ribbon",
            "item_star" to "Star",
            "item_party" to "Party",
            "item_sparkle" to "Sparkle",
            "item_balloon" to "Balloon",
            "item_rainbow" to "Rainbow",
            "item_flowers" to "Flowers",
            "item_castle" to "Castle"
        ),
        AppLanguage.CHINESE_TRADITIONAL to mapOf(
            "reset_records" to "重置紀錄",
            "start" to "開始",
            "best_record" to "最佳紀錄",
            "time_format" to "%.2f秒",
            "light" to "淺色",
            "dark" to "深色",
            "reset_confirm_title" to "確定要重置紀錄嗎？",
            "reset" to "重置",
            "cancel" to "取消",
            "reset_confirm_message" to "最佳紀錄將被刪除。",
            "countdown_go" to "開始！",
            "complete" to "完成！",
            "new_record_title" to "破紀錄了！🎉",
            "new_record_message" to "你完成了全部10題\n並創下新紀錄。恭喜！",
            "well_done" to "辛苦了",
            "best_record_format" to "最佳紀錄 %s",
            "to_main" to "返回主頁",
            "quit_confirm" to "要結束遊戲嗎？",
            "no" to "否",
            "yes" to "是",
            "confirm" to "確認",
            "language" to "語言",
            "level_easy" to "簡單",
            "level_normal" to "普通",
            "help_title" to "難度說明",
            "help_easy_desc" to "• 左側數字：0~99\n• 右側數字：0~10\n• 減法時結果不為負數",
            "help_normal_desc" to "• 左側數字：0~99\n• 右側數字：0~99\n• 加法和減法（可為負數）",
            // ── New strings for stage UX ──
            "resume" to "繼續",
            "new_start" to "選擇運算",
            "select_operation" to "選擇運算",
            "overall_progress" to "整體進度",
            "locked" to "已鎖定",
            "stage_map_title" to "選擇關卡",
            "reset_progress" to "重置進度",
            "reset_progress_confirm_title" to "確定要重置進度嗎？",
            "reset_progress_confirm_message" to "所有關卡記錄將被刪除。",
            "stage_num_format" to "第%d關",
            "resume_hint" to "%s 第%d關",
            "problem_progress" to "%d / 10",
            "result_title_3star" to "太棒了！",
            "result_title_2star" to "做得好！",
            "result_title_1star" to "完成了！",
            "correct_format" to "答對：%d / 10",
            "avg_time_format" to "平均 %.1f秒",
            "retry" to "再試一次",
            "next_stage" to "下一關",
            "to_stage_map" to "關卡地圖",
            "star_cond_3" to "⭐⭐⭐  滿分 + 平均≤6秒",
            "star_cond_2" to "⭐⭐  答對8題以上",
            "star_cond_1" to "⭐  完成全部題目",
            "points_earned" to "獲得 %d P！",
            "hearts_display" to "❤️ %d / %d",
            "next_heart_timer" to "+1 %02d:%02d",
            "total_points_format" to "累計 %d P",
            "avg_label" to "平均",
            "stage_confirm_title" to "開始關卡",
            "stage_confirm_message" to "要開始%s嗎？",
            "stage_start" to "開始",
            "multiple_choice" to "選擇題",
            "fill_in" to "填空題",
            "to_home" to "回主頁",
            // ── Onboarding & Character ──
            "onboarding_title" to "開始數學冒險！",
            "onboarding_desc" to "解開有趣的題目\n收集星星吧！",
            "onboarding_start" to "🚀 開始冒險",
            "select_character" to "選擇你的朋友",
            "character_confirm" to "一起出發！🎉",
            "char_bear" to "熊熊",
            "char_rabbit" to "兔子",
            "char_fox" to "狐狸",
            "char_owl" to "貓頭鷹",
            // ── Daily Quest ──
            "quest_title" to "今日任務",
            "quest_continue" to "繼續 🚀",
            "quest_completed_title" to "今日任務完成！",
            "quest_completed_sub" to "太棒了！今天也認真學習了",
            "quest_desc_progress" to "%s 第%d關 挑戰",
            "quest_desc_review" to "%s 第%d關 複習",
            "quest_desc_new" to "%s 初次嘗試",
            "quest_problems" to "%d題",
            // ── Bottom Nav ──
            "nav_home" to "首頁",
            "nav_report" to "進度",
            "nav_treasure" to "寶箱",
            // ── Learning Report ──
            "report_title" to "學習報告",
            "report_solved" to "完成題目",
            "report_accuracy" to "正確率",
            "report_streak" to "連續學習",
            "report_streak_unit" to "天",
            "report_weekly" to "本週學習記錄",
            "report_badges" to "獲得徽章",
            "report_day_mon" to "一",
            "report_day_tue" to "二",
            "report_day_wed" to "三",
            "report_day_thu" to "四",
            "report_day_fri" to "五",
            "report_day_sat" to "六",
            "report_day_sun" to "日",
            // ── Badges ──
            "badge_first_step" to "第一步",
            "badge_first_step_desc" to "完成第一個關卡",
            "badge_speed_demon" to "閃電手",
            "badge_speed_demon_desc" to "獲得3顆星",
            "badge_perfectionist" to "完美主義者",
            "badge_perfectionist_desc" to "10次獲得3顆星",
            "badge_math_master" to "數學達人",
            "badge_math_master_desc" to "完成所有關卡",
            "badge_consistent" to "堅持不懈",
            "badge_consistent_desc" to "連續7天學習",
            "badge_explorer" to "探險家",
            "badge_explorer_desc" to "挑戰所有運算",
            // ── Parent Settings ──
            "parent_settings_title" to "設定",
            "parent_notifications" to "通知設定",
            "parent_study_notification" to "學習提醒",
            "parent_achievement_notification" to "成就通知",
            "parent_study_management" to "學習管理",
            "parent_time_limit" to "時間限制",
            "parent_daily_goal" to "每日學習目標（分鐘）",
            "parent_display" to "顯示",
            "parent_data" to "資料",
            "parent_account" to "帳號",
            "parent_logout" to "登出",
            // ── Treasure Chest ──
            "treasure_title" to "寶物箱",
            "treasure_level" to "等級",
            "treasure_level_progress" to "距下一等級",
            "treasure_collection" to "寶物收藏",
            "treasure_locked" to "已鎖定",
            // ── Shop ──
            "shop_title" to "商店",
            "shop_coins" to "🪙 %d 金幣",
            "shop_tab_accessory" to "裝扮",
            "shop_tab_effect" to "效果",
            "shop_tab_deco" to "裝飾",
            "shop_buy" to "購買",
            "shop_owned" to "已擁有",
            "shop_equip" to "裝備",
            "shop_equipped" to "已裝備",
            "shop_not_enough" to "金幣不足",
            "item_crown" to "王冠",
            "item_hat" to "帽子",
            "item_glasses" to "眼鏡",
            "item_ribbon" to "緞帶",
            "item_star" to "星星",
            "item_party" to "派對效果",
            "item_sparkle" to "閃亮",
            "item_balloon" to "氣球",
            "item_rainbow" to "彩虹",
            "item_flowers" to "花朵",
            "item_castle" to "城堡"
        ),
        AppLanguage.CHINESE_SIMPLIFIED to mapOf(
            "reset_records" to "重置记录",
            "start" to "开始",
            "best_record" to "最佳记录",
            "time_format" to "%.2f秒",
            "light" to "浅色",
            "dark" to "深色",
            "reset_confirm_title" to "确定要重置记录吗？",
            "reset" to "重置",
            "cancel" to "取消",
            "reset_confirm_message" to "最佳记录将被删除。",
            "countdown_go" to "开始！",
            "complete" to "完成！",
            "new_record_title" to "破纪录了！🎉",
            "new_record_message" to "你完成了全部10题\n并创下新纪录。恭喜！",
            "well_done" to "辛苦了",
            "best_record_format" to "最佳记录 %s",
            "to_main" to "返回主页",
            "quit_confirm" to "要结束游戏吗？",
            "no" to "否",
            "yes" to "是",
            "confirm" to "确认",
            "language" to "语言",
            "level_easy" to "简单",
            "level_normal" to "普通",
            "help_title" to "难度说明",
            "help_easy_desc" to "• 左侧数字：0~99\n• 右侧数字：0~10\n• 减法时结果不为负数",
            "help_normal_desc" to "• 左侧数字：0~99\n• 右侧数字：0~99\n• 加法和减法（可为负数）",
            // ── New strings for stage UX ──
            "resume" to "继续",
            "new_start" to "选择运算",
            "select_operation" to "选择运算",
            "overall_progress" to "整体进度",
            "locked" to "已锁定",
            "stage_map_title" to "选择关卡",
            "reset_progress" to "重置进度",
            "reset_progress_confirm_title" to "确定要重置进度吗？",
            "reset_progress_confirm_message" to "所有关卡记录将被删除。",
            "stage_num_format" to "第%d关",
            "resume_hint" to "%s 第%d关",
            "problem_progress" to "%d / 10",
            "result_title_3star" to "太棒了！",
            "result_title_2star" to "做得好！",
            "result_title_1star" to "完成了！",
            "correct_format" to "答对：%d / 10",
            "avg_time_format" to "平均 %.1f秒",
            "retry" to "再试一次",
            "next_stage" to "下一关",
            "to_stage_map" to "关卡地图",
            "star_cond_3" to "⭐⭐⭐  满分 + 平均≤6秒",
            "star_cond_2" to "⭐⭐  答对8题以上",
            "star_cond_1" to "⭐  完成全部题目",
            "points_earned" to "获得 %d P！",
            "hearts_display" to "❤️ %d / %d",
            "next_heart_timer" to "+1 %02d:%02d",
            "total_points_format" to "累计 %d P",
            "avg_label" to "平均",
            "stage_confirm_title" to "开始关卡",
            "stage_confirm_message" to "要开始%s吗？",
            "stage_start" to "开始",
            "multiple_choice" to "选择题",
            "fill_in" to "填空题",
            "to_home" to "回主页",
            // ── Onboarding & Character ──
            "onboarding_title" to "开始数学冒险！",
            "onboarding_desc" to "解开有趣的题目\n收集星星吧！",
            "onboarding_start" to "🚀 开始冒险",
            "select_character" to "选择你的朋友",
            "character_confirm" to "一起出发！🎉",
            "char_bear" to "小熊",
            "char_rabbit" to "兔子",
            "char_fox" to "狐狸",
            "char_owl" to "猫头鹰",
            // ── Daily Quest ──
            "quest_title" to "今日任务",
            "quest_continue" to "继续 🚀",
            "quest_completed_title" to "今日任务完成！",
            "quest_completed_sub" to "太棒了！今天也认真学习了",
            "quest_desc_progress" to "%s 第%d关 挑战",
            "quest_desc_review" to "%s 第%d关 复习",
            "quest_desc_new" to "%s 初次尝试",
            "quest_problems" to "%d题",
            // ── Bottom Nav ──
            "nav_home" to "首页",
            "nav_report" to "进度",
            "nav_treasure" to "宝箱",
            // ── Learning Report ──
            "report_title" to "学习报告",
            "report_solved" to "完成题目",
            "report_accuracy" to "正确率",
            "report_streak" to "连续学习",
            "report_streak_unit" to "天",
            "report_weekly" to "本周学习记录",
            "report_badges" to "获得徽章",
            "report_day_mon" to "一",
            "report_day_tue" to "二",
            "report_day_wed" to "三",
            "report_day_thu" to "四",
            "report_day_fri" to "五",
            "report_day_sat" to "六",
            "report_day_sun" to "日",
            // ── Badges ──
            "badge_first_step" to "第一步",
            "badge_first_step_desc" to "完成第一个关卡",
            "badge_speed_demon" to "闪电手",
            "badge_speed_demon_desc" to "获得3颗星",
            "badge_perfectionist" to "完美主义者",
            "badge_perfectionist_desc" to "10次获得3颗星",
            "badge_math_master" to "数学达人",
            "badge_math_master_desc" to "完成所有关卡",
            "badge_consistent" to "坚持不懈",
            "badge_consistent_desc" to "连续7天学习",
            "badge_explorer" to "探险家",
            "badge_explorer_desc" to "挑战所有运算",
            // ── Parent Settings ──
            "parent_settings_title" to "设置",
            "parent_notifications" to "通知设置",
            "parent_study_notification" to "学习提醒",
            "parent_achievement_notification" to "成就通知",
            "parent_study_management" to "学习管理",
            "parent_time_limit" to "时间限制",
            "parent_daily_goal" to "每日学习目标（分钟）",
            "parent_display" to "显示",
            "parent_data" to "数据",
            "parent_account" to "账号",
            "parent_logout" to "登出",
            // ── Treasure Chest ──
            "treasure_title" to "宝物箱",
            "treasure_level" to "等级",
            "treasure_level_progress" to "距下一等级",
            "treasure_collection" to "宝物收藏",
            "treasure_locked" to "已锁定",
            // ── Shop ──
            "shop_title" to "商店",
            "shop_coins" to "🪙 %d 金币",
            "shop_tab_accessory" to "装扮",
            "shop_tab_effect" to "效果",
            "shop_tab_deco" to "装饰",
            "shop_buy" to "购买",
            "shop_owned" to "已拥有",
            "shop_equip" to "装备",
            "shop_equipped" to "已装备",
            "shop_not_enough" to "金币不足",
            "item_crown" to "王冠",
            "item_hat" to "帽子",
            "item_glasses" to "眼镜",
            "item_ribbon" to "丝带",
            "item_star" to "星星",
            "item_party" to "派对效果",
            "item_sparkle" to "闪闪发光",
            "item_balloon" to "气球",
            "item_rainbow" to "彩虹",
            "item_flowers" to "花朵",
            "item_castle" to "城堡"
        ),
        AppLanguage.JAPANESE to mapOf(
            "reset_records" to "記録をリセット",
            "start" to "スタート",
            "best_record" to "最高記録",
            "time_format" to "%.2f秒",
            "light" to "ライト",
            "dark" to "ダーク",
            "reset_confirm_title" to "記録をリセットしますか？",
            "reset" to "リセット",
            "cancel" to "キャンセル",
            "reset_confirm_message" to "最高記録が削除されます。",
            "countdown_go" to "スタート！",
            "complete" to "完了！",
            "new_record_title" to "新記録達成！🎉",
            "new_record_message" to "10問すべて解いて\n新記録を達成しました。おめでとう！",
            "well_done" to "お疲れ様でした",
            "best_record_format" to "最高記録 %s",
            "to_main" to "メインへ",
            "quit_confirm" to "ゲームを終了しますか？",
            "no" to "いいえ",
            "yes" to "はい",
            "confirm" to "確認",
            "language" to "言語",
            "level_easy" to "かんたん",
            "level_normal" to "ふつう",
            "help_title" to "レベル説明",
            "help_easy_desc" to "• 左の数字：0~99\n• 右の数字：0~10\n• 引き算は結果がマイナスにならない",
            "help_normal_desc" to "• 左の数字：0~99\n• 右の数字：0~99\n• 足し算と引き算（マイナス可）",
            // ── New strings for stage UX ──
            "resume" to "続ける",
            "new_start" to "演算を選ぶ",
            "select_operation" to "演算を選択",
            "overall_progress" to "全体の進捗",
            "locked" to "ロック中",
            "stage_map_title" to "ステージ選択",
            "reset_progress" to "進捗をリセット",
            "reset_progress_confirm_title" to "進捗をリセットしますか？",
            "reset_progress_confirm_message" to "すべてのステージ記録が削除されます。",
            "stage_num_format" to "第%dステージ",
            "resume_hint" to "%s 第%dステージ",
            "problem_progress" to "%d / 10",
            "result_title_3star" to "完璧！",
            "result_title_2star" to "よくできました！",
            "result_title_1star" to "クリア！",
            "correct_format" to "正解: %d / 10",
            "avg_time_format" to "平均 %.1f秒",
            "retry" to "もう一度",
            "next_stage" to "次のステージへ",
            "to_stage_map" to "ステージマップ",
            "star_cond_3" to "⭐⭐⭐  満点 + 平均6秒以内",
            "star_cond_2" to "⭐⭐  8問以上正解",
            "star_cond_1" to "⭐  全問クリア",
            "points_earned" to "%d P 獲得！",
            "hearts_display" to "❤️ %d / %d",
            "next_heart_timer" to "+1 %02d:%02d",
            "total_points_format" to "累計 %d P",
            "avg_label" to "平均",
            "stage_confirm_title" to "ステージ開始",
            "stage_confirm_message" to "%sを始めますか？",
            "stage_start" to "始める",
            "multiple_choice" to "選択式",
            "fill_in" to "記述式",
            "to_home" to "ホームへ",
            // ── Onboarding & Character ──
            "onboarding_title" to "数学の冒険を始めよう！",
            "onboarding_desc" to "楽しい問題を解いて\n星を集めよう！",
            "onboarding_start" to "🚀 冒険スタート",
            "select_character" to "友だちを選ぼう",
            "character_confirm" to "一緒に行こう！🎉",
            "char_bear" to "クマ",
            "char_rabbit" to "ウサギ",
            "char_fox" to "キツネ",
            "char_owl" to "フクロウ",
            // ── Daily Quest ──
            "quest_title" to "今日のクエスト",
            "quest_continue" to "続ける 🚀",
            "quest_completed_title" to "今日のクエスト達成！",
            "quest_completed_sub" to "すごい！今日もがんばりました",
            "quest_desc_progress" to "%s 第%dステージ 挑戦",
            "quest_desc_review" to "%s 第%dステージ 復習",
            "quest_desc_new" to "%s はじめての挑戦",
            "quest_problems" to "%d問",
            // ── Bottom Nav ──
            "nav_home" to "ホーム",
            "nav_report" to "進捗",
            "nav_treasure" to "宝箱",
            // ── Learning Report ──
            "report_title" to "学習レポート",
            "report_solved" to "解いた問題",
            "report_accuracy" to "正解率",
            "report_streak" to "連続学習",
            "report_streak_unit" to "日",
            "report_weekly" to "週間学習記録",
            "report_badges" to "獲得バッジ",
            "report_day_mon" to "月",
            "report_day_tue" to "火",
            "report_day_wed" to "水",
            "report_day_thu" to "木",
            "report_day_fri" to "金",
            "report_day_sat" to "土",
            "report_day_sun" to "日",
            // ── Badges ──
            "badge_first_step" to "はじめの一歩",
            "badge_first_step_desc" to "最初のステージをクリア",
            "badge_speed_demon" to "スピードスター",
            "badge_speed_demon_desc" to "3つ星を獲得",
            "badge_perfectionist" to "パーフェクト",
            "badge_perfectionist_desc" to "3つ星を10回達成",
            "badge_math_master" to "算数マスター",
            "badge_math_master_desc" to "全ステージクリア",
            "badge_consistent" to "継続力",
            "badge_consistent_desc" to "7日連続学習",
            "badge_explorer" to "探検家",
            "badge_explorer_desc" to "全演算に挑戦",
            // ── Parent Settings ──
            "parent_settings_title" to "設定",
            "parent_notifications" to "通知設定",
            "parent_study_notification" to "学習リマインダー",
            "parent_achievement_notification" to "実績通知",
            "parent_study_management" to "学習管理",
            "parent_time_limit" to "時間制限",
            "parent_daily_goal" to "1日の学習目標（分）",
            "parent_display" to "表示",
            "parent_data" to "データ",
            "parent_account" to "アカウント",
            "parent_logout" to "ログアウト",
            // ── Treasure Chest ──
            "treasure_title" to "宝物箱",
            "treasure_level" to "レベル",
            "treasure_level_progress" to "次のレベルまで",
            "treasure_collection" to "コレクション",
            "treasure_locked" to "ロック中",
            // ── Shop ──
            "shop_title" to "ショップ",
            "shop_coins" to "🪙 %dコイン",
            "shop_tab_accessory" to "コーデ",
            "shop_tab_effect" to "エフェクト",
            "shop_tab_deco" to "デコ",
            "shop_buy" to "購入",
            "shop_owned" to "所持",
            "shop_equip" to "装備",
            "shop_equipped" to "装備中",
            "shop_not_enough" to "コイン不足",
            "item_crown" to "王冠",
            "item_hat" to "帽子",
            "item_glasses" to "メガネ",
            "item_ribbon" to "リボン",
            "item_star" to "お星様",
            "item_party" to "パーティ",
            "item_sparkle" to "キラキラ",
            "item_balloon" to "バルーン",
            "item_rainbow" to "虹",
            "item_flowers" to "お花",
            "item_castle" to "お城"
        )
    )

    fun string(key: String, lang: AppLanguage, vararg args: Any): String {
        val template = strings[lang]?.get(key) ?: strings[AppLanguage.ENGLISH]!![key] ?: key
        return if (args.isEmpty()) template else kmpFormat(template, *args)
    }
}

/** Multiplatform string formatter — supports %.Nf, %s, and %d specifiers. */
private fun kmpFormat(template: String, vararg args: Any): String {
    val result = StringBuilder()
    var argIndex = 0
    var i = 0
    while (i < template.length) {
        if (template[i] == '%' && i + 1 < template.length) {
            val rest = template.substring(i + 1)
            val floatMatch = Regex("^\\.(\\d+)f").find(rest)
            val paddedIntMatch = Regex("^0(\\d+)d").find(rest)
            val stringMatch = rest.startsWith("s")
            val intMatch = rest.startsWith("d")
            when {
                floatMatch != null -> {
                    val decimals = floatMatch.groupValues[1].toInt()
                    val value = (args.getOrNull(argIndex++) as? Number)?.toFloat() ?: 0f
                    result.append(formatFloat(value, decimals))
                    i += 1 + floatMatch.value.length
                }
                paddedIntMatch != null -> {
                    val width = paddedIntMatch.groupValues[1].toInt()
                    val value = (args.getOrNull(argIndex++) as? Number)?.toInt() ?: 0
                    result.append(value.toString().padStart(width, '0'))
                    i += 1 + paddedIntMatch.value.length
                }
                stringMatch -> {
                    result.append(args.getOrNull(argIndex++)?.toString() ?: "")
                    i += 2
                }
                intMatch -> {
                    result.append((args.getOrNull(argIndex++) as? Number)?.toInt() ?: 0)
                    i += 2
                }
                else -> {
                    result.append('%')
                    i++
                }
            }
        } else {
            result.append(template[i])
            i++
        }
    }
    return result.toString()
}

private fun formatFloat(value: Float, decimals: Int): String {
    val absValue = if (value < 0f) -value else value
    val sign = if (value < 0f) "-" else ""
    val multiplier = when (decimals) {
        0 -> 1; 1 -> 10; 2 -> 100; 3 -> 1000; else -> 100
    }
    val scaled = (absValue * multiplier + 0.5f).toInt()
    val intPart = scaled / multiplier
    val fracPart = scaled % multiplier
    return if (decimals == 0) "$sign$intPart"
    else "$sign$intPart.${fracPart.toString().padStart(decimals, '0')}"
}
