package com.mathapp.practice.ui

enum class AppLanguage(val code: String, val displayName: String) {
    KOREAN("ko", "한국어"),
    ENGLISH("en", "English"),
    CHINESE_TRADITIONAL("zh-Hant", "中文(繁體)"),
    CHINESE_SIMPLIFIED("zh-Hans", "中文(简体)"),
    JAPANESE("ja", "日本語");

    companion object {
        fun fromCode(code: String): AppLanguage = entries.find { it.code == code } ?: ENGLISH
    }
}

object L10n {
    private val strings = mapOf(
        AppLanguage.KOREAN to mapOf(
            "reset_records" to "기록 초기화",
            "start" to "시작",
            "best_record" to "최고 기록",
            "time_format" to "%.2f초",
            "light" to "라이트",
            "dark" to "다크",
            "reset_confirm_title" to "기록을 초기화하시겠습니까?",
            "reset" to "초기화",
            "cancel" to "취소",
            "reset_confirm_message" to "최고 기록이 삭제됩니다.",
            "countdown_go" to "시작!",
            "complete" to "완료!",
            "new_record_title" to "최고 기록을 경신했어요! 🎉",
            "new_record_message" to "10문제를 모두 풀고\n새로운 기록을 세웠어요. 축하해요!",
            "well_done" to "수고하셨습니다",
            "best_record_format" to "최고 기록 %s",
            "to_main" to "메인으로",
            "quit_confirm" to "그만하시겠습니까?",
            "no" to "아니오",
            "yes" to "예",
            "confirm" to "확인",
            "language" to "언어",
            "level_easy" to "쉬움",
            "level_normal" to "보통",
            "help_title" to "레벨 설명",
            "help_easy_desc" to "• 왼쪽 숫자: 0~99\n• 오른쪽 숫자: 0~10\n• 뺄셈 시 결과가 음수가 되지 않음",
            "help_normal_desc" to "• 왼쪽 숫자: 0~99\n• 오른쪽 숫자: 0~99\n• 덧셈과 뺄셈 (음수 가능)",
            // ── New strings for stage UX ──
            "resume" to "이어서 하기",
            "new_start" to "새로 시작하기",
            "select_operation" to "연산 선택",
            "overall_progress" to "전체 진척도",
            "locked" to "잠김",
            "stage_map_title" to "스테이지 선택",
            "reset_progress" to "진척도 초기화",
            "reset_progress_confirm_title" to "진척도를 초기화하시겠습니까?",
            "reset_progress_confirm_message" to "모든 스테이지 기록이 삭제됩니다.",
            "stage_num_format" to "%d단계",
            "resume_hint" to "%s %d단계",
            "problem_progress" to "%d / 10",
            "result_title_3star" to "완벽해요!",
            "result_title_2star" to "잘했어요!",
            "result_title_1star" to "완주했어요!",
            "correct_format" to "맞힌 문제: %d / 10",
            "avg_time_format" to "평균 %.1f초",
            "avg_label" to "평균",
            "retry" to "다시 하기",
            "next_stage" to "다음 단계로",
            "to_stage_map" to "스테이지 맵으로",
            "star_cond_3" to "⭐⭐⭐  만점 + 평균 6초 이하",
            "star_cond_2" to "⭐⭐  8문제 이상 정답",
            "star_cond_1" to "⭐  완주 성공",
            "points_earned" to "%d 별점수 획득!",
            "hearts_display" to "❤️ %d / %d",
            "next_heart_timer" to "+1 %02d:%02d",
            "total_points_format" to "⭐ %d 별점수",
            // ── Onboarding & Character ──
            "onboarding_title" to "셈토끼와 연산 모험을 시작해요!",
            "onboarding_desc" to "재미있는 문제를 풀면서\n모험 친구와 별을 모아보아요!",
            "onboarding_start" to "🚀 모험 시작하기",
            "select_character" to "오늘 함께할 모험 친구를 골라요",
            "character_confirm" to "모험 친구와 함께하기 🎉",
            "char_bear" to "곰돌이",
            "char_rabbit" to "토끼",
            "char_fox" to "여우",
            "char_owl" to "부엉이",
            "char_cat" to "고양이",
            "char_dog" to "강아지",
            // ── Daily Quest ──
            "quest_title" to "오늘의 퀘스트",
            "quest_continue" to "계속하기 🚀",
            "quest_completed_title" to "오늘의 퀘스트 완료!",
            "quest_completed_sub" to "대단해요! 셈토끼와 오늘의 모험을 완주했어요!",
            "quest_desc_progress" to "%s %d단계 도전",
            "quest_desc_review" to "%s %d단계 복습",
            "quest_desc_new" to "%s 처음 시작",
            "quest_problems" to "%d문제",
            "quest_progress_start" to "시작해 보자! 🎯",
            "quest_progress_remaining" to "%d개만 더! 💪",
            "quest_buddy_hint" to "오늘도 같이하자! 💪",
            // ── Bottom Nav ──
            "nav_home" to "홈",
            "nav_report" to "탐험 기록",
            "nav_treasure" to "별보물함",
            // ── Learning Report ──
            "report_title" to "탐험 기록",
            "report_solved" to "완료한 문제",
            "report_accuracy" to "정확도",
            "report_streak" to "연속 학습",
            "report_streak_unit" to "일",
            "report_weekly" to "주간 학습 기록",
            "report_badges" to "획득한 배지",
            "report_day_mon" to "월",
            "report_day_tue" to "화",
            "report_day_wed" to "수",
            "report_day_thu" to "목",
            "report_day_fri" to "금",
            "report_day_sat" to "토",
            "report_day_sun" to "일",
            // ── Badges ──
            "badge_first_step" to "첫 걸음",
            "badge_first_step_desc" to "첫 스테이지 클리어",
            "badge_speed_demon" to "번개 같은 손",
            "badge_speed_demon_desc" to "별 3개 획득",
            "badge_perfectionist" to "완벽주의자",
            "badge_perfectionist_desc" to "별 3개 10회 달성",
            "badge_math_master" to "수학 달인",
            "badge_math_master_desc" to "모든 스테이지 클리어",
            "badge_consistent" to "꾸준함",
            "badge_consistent_desc" to "7일 연속 학습",
            "badge_explorer" to "탐험가",
            "badge_explorer_desc" to "모든 연산 도전",
            // ── Parent Settings ──
            "parent_settings_title" to "설정",
            "parent_notifications" to "알림 설정",
            "parent_study_notification" to "학습 알림",
            "parent_achievement_notification" to "성과 알림",
            "parent_study_management" to "학습 관리",
            "parent_time_limit" to "시간 제한",
            "parent_daily_goal" to "일일 학습 목표 (분)",
            "parent_display" to "화면",
            "parent_data" to "데이터",
            "parent_account" to "계정",
            "parent_logout" to "로그아웃",
            // ── Treasure Chest ──
            "treasure_title" to "별보물함",
            "treasure_level" to "레벨",
            "treasure_level_progress" to "다음 레벨까지",
            "treasure_collection" to "보물 컬렉션",
            "treasure_locked" to "잠김",
            "treasure_set_featured" to "대표 보물로 전시하기",
            "treasure_is_featured" to "대표 보물로 전시 중 ✨",
            "treasure_hint_points" to "다음 보물까지 %dP 남았어요.",
            "treasure_featured_section" to "대표 보물 전시대",
            "treasure_achieved" to "획득 완료!",
            "treasure_not_yet" to "아직 잠긴 보물이에요.",
            "treasure_name_0" to "황금 열쇠",
            "treasure_name_1" to "루비 반지",
            "treasure_name_2" to "모험 지도",
            "treasure_name_3" to "황금 항아리",
            "treasure_name_4" to "용사의 검",
            "treasure_name_5" to "수호의 방패",
            "treasure_name_6" to "신비한 보석",
            "treasure_name_7" to "빛나는 왕관",
            "treasure_name_8" to "별의 보석",
            "treasure_desc_0" to "처음 도전을 시작한 용기를 기념하는 보물",
            "treasure_desc_1" to "꾸준히 노력해서 얻은 소중한 보물",
            "treasure_desc_2" to "여러 연산에 도전한 탐험 정신을 기념하는 보물",
            "treasure_desc_3" to "끊임없는 노력으로 가득 채워진 보물",
            "treasure_desc_4" to "어려운 도전을 이겨낸 용기의 상징",
            "treasure_desc_5" to "흔들리지 않고 문제를 풀어온 인내의 상징",
            "treasure_desc_6" to "별 3개를 여러 번 모은 집중력을 기념하는 보물",
            "treasure_desc_7" to "수학의 왕이 될 자질을 보여준 최고의 보물",
            "treasure_desc_8" to "모든 도전을 완성한 전설의 보물",
            "treasure_praise_0" to "처음 끝까지 해냈어요. 정말 멋진 시작이에요!",
            "treasure_praise_1" to "꾸준히 포기하지 않고 도전했어요!",
            "treasure_praise_2" to "어려운 문제도 포기하지 않고 도전했어요!",
            "treasure_praise_3" to "열심히 쌓아온 노력이 빛나고 있어요!",
            "treasure_praise_4" to "어려운 수학도 겁내지 않는 진짜 용사예요!",
            "treasure_praise_5" to "차근차근 풀어온 실력이 든든한 방패가 되었어요!",
            "treasure_praise_6" to "차곡차곡 모은 별들이 멋진 보물이 되었어요!",
            "treasure_praise_7" to "정말 대단해요! 수학의 왕이 되어가고 있어요!",
            "treasure_praise_8" to "모든 도전을 완성한 진정한 수학 영웅이에요!",
            "stage_confirm_title" to "스테이지 시작",
            "stage_confirm_message" to "%s을(를) 시작하시겠습니까?",
            "stage_start" to "시작하기",
            "multiple_choice" to "객관식",
            "fill_in" to "주관식",
            "to_home" to "메인으로",
            // ── Shop ──
            "shop_title" to "꾸미기 상점",
            "shop_coins" to "🪙 %d 별코인",
            "shop_tab_accessory" to "꾸미기",
            "shop_tab_effect" to "효과",
            "shop_tab_deco" to "장식",
            "shop_buy" to "구매하기",
            "shop_owned" to "보유 중",
            "shop_equip" to "장착하기",
            "shop_equipped" to "장착 중",
            "shop_not_enough" to "별코인 부족",
            "shop_cancel" to "취소",
            "shop_confirm_buy_title" to "구매할까요?",
            "shop_confirm_buy_cost" to "🪙 %d 별코인이 사용돼요.",
            "shop_bought_title" to "구매했어요!",
            "shop_equip_now_question" to "지금 장착할까요?",
            "shop_later" to "나중에",
            "item_crown" to "왕관",
            "item_hat" to "모자",
            "item_glasses" to "안경",
            "item_ribbon" to "리본",
            "item_star" to "별 장식",
            "item_party" to "파티 효과",
            "item_sparkle" to "반짝임",
            "item_balloon" to "풍선",
            "item_rainbow" to "무지개",
            "item_flowers" to "꽃 장식",
            "item_castle" to "성",
            "shop_tab_head" to "머리 장식",
            "shop_tab_badge" to "뱃지",
            "shop_tab_bg" to "배경",
            "portrait_title" to "친구 꾸미기",
            "portrait_no_items" to "보유한 아이템이 없어요",
            "nav_character" to "친구",
            "item_medal" to "메달",
            "item_diamond" to "다이아몬드",
            "item_fire" to "불꽃",
            "item_shine" to "빛나는 별",
            "item_night" to "밤하늘",
            "item_ocean" to "바다",
            "item_spring" to "봄 배경",
            "item_flower" to "꽃 장식"
        ),
        AppLanguage.ENGLISH to mapOf(
            "reset_records" to "Reset Records",
            "start" to "Start",
            "best_record" to "Best Record",
            "time_format" to "%.2fs",
            "light" to "Light",
            "dark" to "Dark",
            "reset_confirm_title" to "Reset your best record?",
            "reset" to "Reset",
            "cancel" to "Cancel",
            "reset_confirm_message" to "Your best record will be deleted.",
            "countdown_go" to "Go!",
            "complete" to "Complete!",
            "new_record_title" to "New Record! 🎉",
            "new_record_message" to "You solved all 10 problems\nand set a new record. Congratulations!",
            "well_done" to "Well done!",
            "best_record_format" to "Best record %s",
            "to_main" to "To Main",
            "quit_confirm" to "Quit the game?",
            "no" to "No",
            "yes" to "Yes",
            "confirm" to "Confirm",
            "language" to "Language",
            "level_easy" to "Easy",
            "level_normal" to "Normal",
            "help_title" to "Level Guide",
            "help_easy_desc" to "• Left number: 0~99\n• Right number: 0~10\n• Subtraction: result is never negative",
            "help_normal_desc" to "• Left number: 0~99\n• Right number: 0~99\n• Addition and subtraction (negative allowed)",
            // ── New strings for stage UX ──
            "resume" to "Continue",
            "new_start" to "Choose Operation",
            "select_operation" to "Select Operation",
            "overall_progress" to "Overall Progress",
            "locked" to "Locked",
            "stage_map_title" to "Select Stage",
            "reset_progress" to "Reset Progress",
            "reset_progress_confirm_title" to "Reset all progress?",
            "reset_progress_confirm_message" to "All stage records will be deleted.",
            "stage_num_format" to "Stage %d",
            "resume_hint" to "%s Stage %d",
            "problem_progress" to "%d / 10",
            "result_title_3star" to "Perfect!",
            "result_title_2star" to "Great job!",
            "result_title_1star" to "You did it!",
            "correct_format" to "Correct: %d / 10",
            "avg_time_format" to "Avg %.1fs",
            "avg_label" to "Avg",
            "retry" to "Try Again",
            "next_stage" to "Next Stage",
            "to_stage_map" to "Stage Map",
            "star_cond_3" to "⭐⭐⭐  Perfect score + avg ≤ 6s",
            "star_cond_2" to "⭐⭐  8 or more correct",
            "star_cond_1" to "⭐  Finish all 10",
            "points_earned" to "%d star pts earned!",
            "hearts_display" to "❤️ %d / %d",
            "next_heart_timer" to "+1 %02d:%02d",
            "total_points_format" to "⭐ %d star pts",
            // ── Onboarding & Character ──
            "onboarding_title" to "Start Your Adventure with Semtokki!",
            "onboarding_desc" to "Solve fun problems and\ncollect stars with your adventure buddy!",
            "onboarding_start" to "🚀 Start Adventure",
            "select_character" to "Choose Your Adventure Buddy",
            "character_confirm" to "Adventure Together! 🎉",
            "char_bear" to "Bear",
            "char_rabbit" to "Rabbit",
            "char_fox" to "Fox",
            "char_owl" to "Owl",
            "char_cat" to "Cat",
            "char_dog" to "Dog",
            // ── Daily Quest ──
            "quest_title" to "Today's Quest",
            "quest_continue" to "Continue 🚀",
            "quest_completed_title" to "Quest Complete!",
            "quest_completed_sub" to "Amazing! Today's adventure is complete!",
            "quest_desc_progress" to "%s Stage %d Challenge",
            "quest_desc_review" to "%s Stage %d Review",
            "quest_desc_new" to "%s First Steps",
            "quest_problems" to "%d problems",
            "quest_progress_start" to "Let's start! 🎯",
            "quest_progress_remaining" to "%d more to go! 💪",
            "quest_buddy_hint" to "Let's do this! 💪",
            // ── Bottom Nav ──
            "nav_home" to "Home",
            "nav_report" to "Adventure Log",
            "nav_treasure" to "Star Chest",
            // ── Learning Report ──
            "report_title" to "Adventure Log",
            "report_solved" to "Problems Done",
            "report_accuracy" to "Accuracy",
            "report_streak" to "Streak",
            "report_streak_unit" to " days",
            "report_weekly" to "Weekly Activity",
            "report_badges" to "Badges",
            "report_day_mon" to "Mon",
            "report_day_tue" to "Tue",
            "report_day_wed" to "Wed",
            "report_day_thu" to "Thu",
            "report_day_fri" to "Fri",
            "report_day_sat" to "Sat",
            "report_day_sun" to "Sun",
            // ── Badges ──
            "badge_first_step" to "First Step",
            "badge_first_step_desc" to "Clear your first stage",
            "badge_speed_demon" to "Speed Demon",
            "badge_speed_demon_desc" to "Earn 3 stars on a stage",
            "badge_perfectionist" to "Perfectionist",
            "badge_perfectionist_desc" to "Get 3 stars 10 times",
            "badge_math_master" to "Math Master",
            "badge_math_master_desc" to "Clear all 40 stages",
            "badge_consistent" to "Consistent",
            "badge_consistent_desc" to "Play 7 days in a row",
            "badge_explorer" to "Explorer",
            "badge_explorer_desc" to "Try all operations",
            // ── Parent Settings ──
            "parent_settings_title" to "Settings",
            "parent_notifications" to "Notifications",
            "parent_study_notification" to "Study Reminders",
            "parent_achievement_notification" to "Achievement Alerts",
            "parent_study_management" to "Study Management",
            "parent_time_limit" to "Time Limit",
            "parent_daily_goal" to "Daily Goal (minutes)",
            "parent_display" to "Display",
            "parent_data" to "Data",
            "parent_account" to "Account",
            "parent_logout" to "Log Out",
            // ── Treasure Chest ──
            "treasure_title" to "Star Chest",
            "treasure_level" to "Level",
            "treasure_level_progress" to "To next level",
            "treasure_collection" to "Collection",
            "treasure_locked" to "Locked",
            "treasure_set_featured" to "Set as Featured Treasure",
            "treasure_is_featured" to "Currently Featured ✨",
            "treasure_hint_points" to "%dP until next treasure.",
            "treasure_featured_section" to "Featured Treasure",
            "treasure_achieved" to "Achieved!",
            "treasure_not_yet" to "This treasure is still locked.",
            "treasure_name_0" to "Golden Key",
            "treasure_name_1" to "Ruby Ring",
            "treasure_name_2" to "Adventure Map",
            "treasure_name_3" to "Golden Jar",
            "treasure_name_4" to "Hero's Sword",
            "treasure_name_5" to "Guardian Shield",
            "treasure_name_6" to "Mystic Gem",
            "treasure_name_7" to "Shining Crown",
            "treasure_name_8" to "Star of Legend",
            "treasure_desc_0" to "A treasure honoring the courage to start your first adventure.",
            "treasure_desc_1" to "A precious treasure earned through steady effort.",
            "treasure_desc_2" to "A treasure honoring the explorer spirit of tackling many problems.",
            "treasure_desc_3" to "A treasure filled with your endless effort and dedication.",
            "treasure_desc_4" to "A symbol of the courage to overcome difficult challenges.",
            "treasure_desc_5" to "A symbol of the patience to keep solving without giving up.",
            "treasure_desc_6" to "A treasure celebrating the focus that earned many 3-star scores.",
            "treasure_desc_7" to "The greatest treasure, proving you have what it takes to be a math king.",
            "treasure_desc_8" to "The legendary treasure of one who completed every challenge.",
            "treasure_praise_0" to "You made it to the end! What an amazing start!",
            "treasure_praise_1" to "You kept going without giving up!",
            "treasure_praise_2" to "You tackled hard problems without giving up!",
            "treasure_praise_3" to "All your hard work is shining bright!",
            "treasure_praise_4" to "A true hero who isn't afraid of hard math!",
            "treasure_praise_5" to "Your steady practice has become a strong shield!",
            "treasure_praise_6" to "All those stars you collected made a wonderful treasure!",
            "treasure_praise_7" to "Amazing! You're on your way to becoming a math king!",
            "treasure_praise_8" to "A true math hero who completed every challenge!",
            "stage_confirm_title" to "Start Stage",
            "stage_confirm_message" to "Start %s?",
            "stage_start" to "Start",
            "multiple_choice" to "Multiple Choice",
            "fill_in" to "Fill In",
            "to_home" to "Home",
            // ── Shop ──
            "shop_title" to "Outfit Shop",
            "shop_coins" to "🪙 %d star coins",
            "shop_tab_accessory" to "Outfit",
            "shop_tab_effect" to "Effects",
            "shop_tab_deco" to "Decor",
            "shop_buy" to "Buy",
            "shop_owned" to "Owned",
            "shop_equip" to "Equip",
            "shop_equipped" to "Equipped",
            "shop_not_enough" to "Not enough",
            "shop_cancel" to "Cancel",
            "shop_confirm_buy_title" to "Purchase?",
            "shop_confirm_buy_cost" to "Uses 🪙 %d star coins.",
            "shop_bought_title" to "Purchased!",
            "shop_equip_now_question" to "Equip now?",
            "shop_later" to "Later",
            "item_crown" to "Crown",
            "item_hat" to "Hat",
            "item_glasses" to "Glasses",
            "item_ribbon" to "Ribbon",
            "item_star" to "Star",
            "item_party" to "Party",
            "item_sparkle" to "Sparkle",
            "item_balloon" to "Balloon",
            "item_rainbow" to "Rainbow",
            "item_flowers" to "Flowers",
            "item_castle" to "Castle",
            "shop_tab_head" to "Head",
            "shop_tab_badge" to "Badge",
            "shop_tab_bg" to "Background",
            "portrait_title" to "Friend Style",
            "portrait_no_items" to "No items owned yet",
            "nav_character" to "Buddy",
            "item_medal" to "Medal",
            "item_diamond" to "Diamond",
            "item_fire" to "Flame",
            "item_shine" to "Shine",
            "item_night" to "Night Sky",
            "item_ocean" to "Ocean",
            "item_spring" to "Spring",
            "item_flower" to "Flower"
        ),
        AppLanguage.CHINESE_TRADITIONAL to mapOf(
            "reset_records" to "重置紀錄",
            "start" to "開始",
            "best_record" to "最佳紀錄",
            "time_format" to "%.2f秒",
            "light" to "淺色",
            "dark" to "深色",
            "reset_confirm_title" to "確定要重置紀錄嗎？",
            "reset" to "重置",
            "cancel" to "取消",
            "reset_confirm_message" to "最佳紀錄將被刪除。",
            "countdown_go" to "開始！",
            "complete" to "完成！",
            "new_record_title" to "破紀錄了！🎉",
            "new_record_message" to "你完成了全部10題\n並創下新紀錄。恭喜！",
            "well_done" to "辛苦了",
            "best_record_format" to "最佳紀錄 %s",
            "to_main" to "返回主頁",
            "quit_confirm" to "要結束遊戲嗎？",
            "no" to "否",
            "yes" to "是",
            "confirm" to "確認",
            "language" to "語言",
            "level_easy" to "簡單",
            "level_normal" to "普通",
            "help_title" to "難度說明",
            "help_easy_desc" to "• 左側數字：0~99\n• 右側數字：0~10\n• 減法時結果不為負數",
            "help_normal_desc" to "• 左側數字：0~99\n• 右側數字：0~99\n• 加法和減法（可為負數）",
            // ── New strings for stage UX ──
            "resume" to "繼續",
            "new_start" to "選擇運算",
            "select_operation" to "選擇運算",
            "overall_progress" to "整體進度",
            "locked" to "已鎖定",
            "stage_map_title" to "選擇關卡",
            "reset_progress" to "重置進度",
            "reset_progress_confirm_title" to "確定要重置進度嗎？",
            "reset_progress_confirm_message" to "所有關卡記錄將被刪除。",
            "stage_num_format" to "第%d關",
            "resume_hint" to "%s 第%d關",
            "problem_progress" to "%d / 10",
            "result_title_3star" to "太棒了！",
            "result_title_2star" to "做得好！",
            "result_title_1star" to "完成了！",
            "correct_format" to "答對：%d / 10",
            "avg_time_format" to "平均 %.1f秒",
            "retry" to "再試一次",
            "next_stage" to "下一關",
            "to_stage_map" to "關卡地圖",
            "star_cond_3" to "⭐⭐⭐  滿分 + 平均≤6秒",
            "star_cond_2" to "⭐⭐  答對8題以上",
            "star_cond_1" to "⭐  完成全部題目",
            "points_earned" to "獲得 %d 星點數！",
            "hearts_display" to "❤️ %d / %d",
            "next_heart_timer" to "+1 %02d:%02d",
            "total_points_format" to "⭐ %d 星點數",
            "avg_label" to "平均",
            "stage_confirm_title" to "開始關卡",
            "stage_confirm_message" to "要開始%s嗎？",
            "stage_start" to "開始",
            "multiple_choice" to "選擇題",
            "fill_in" to "填空題",
            "to_home" to "回主頁",
            // ── Onboarding & Character ──
            "onboarding_title" to "開始賽兔的連算冒險！",
            "onboarding_desc" to "解開有趣的題目\n與冒險夥伴一起收集星星吧！",
            "onboarding_start" to "🚀 開始冒險",
            "select_character" to "選擇今天的冒險夥伴",
            "character_confirm" to "與夥伴一起出發！🎉",
            "char_bear" to "熊熊",
            "char_rabbit" to "兔子",
            "char_fox" to "狐狸",
            "char_owl" to "貓頭鷹",
            "char_cat" to "貓咪",
            "char_dog" to "小狗",
            // ── Daily Quest ──
            "quest_title" to "今日任務",
            "quest_continue" to "繼續 🚀",
            "quest_completed_title" to "今日任務完成！",
            "quest_completed_sub" to "太棒了！今天的冒險完成了！",
            "quest_desc_progress" to "%s 第%d關 挑戰",
            "quest_desc_review" to "%s 第%d關 複習",
            "quest_desc_new" to "%s 初次嘗試",
            "quest_problems" to "%d題",
            "quest_progress_start" to "開始吧！🎯",
            "quest_progress_remaining" to "再 %d 題就完成！💪",
            "quest_buddy_hint" to "今天一起加油！💪",
            // ── Bottom Nav ──
            "nav_home" to "首頁",
            "nav_report" to "探險記錄",
            "nav_treasure" to "星寶箱",
            // ── Learning Report ──
            "report_title" to "探險記錄",
            "report_solved" to "完成題目",
            "report_accuracy" to "正確率",
            "report_streak" to "連續學習",
            "report_streak_unit" to "天",
            "report_weekly" to "本週學習記錄",
            "report_badges" to "獲得徽章",
            "report_day_mon" to "一",
            "report_day_tue" to "二",
            "report_day_wed" to "三",
            "report_day_thu" to "四",
            "report_day_fri" to "五",
            "report_day_sat" to "六",
            "report_day_sun" to "日",
            // ── Badges ──
            "badge_first_step" to "第一步",
            "badge_first_step_desc" to "完成第一個關卡",
            "badge_speed_demon" to "閃電手",
            "badge_speed_demon_desc" to "獲得3顆星",
            "badge_perfectionist" to "完美主義者",
            "badge_perfectionist_desc" to "10次獲得3顆星",
            "badge_math_master" to "數學達人",
            "badge_math_master_desc" to "完成所有關卡",
            "badge_consistent" to "堅持不懈",
            "badge_consistent_desc" to "連續7天學習",
            "badge_explorer" to "探險家",
            "badge_explorer_desc" to "挑戰所有運算",
            // ── Parent Settings ──
            "parent_settings_title" to "設定",
            "parent_notifications" to "通知設定",
            "parent_study_notification" to "學習提醒",
            "parent_achievement_notification" to "成就通知",
            "parent_study_management" to "學習管理",
            "parent_time_limit" to "時間限制",
            "parent_daily_goal" to "每日學習目標（分鐘）",
            "parent_display" to "顯示",
            "parent_data" to "資料",
            "parent_account" to "帳號",
            "parent_logout" to "登出",
            // ── Treasure Chest ──
            "treasure_title" to "星寶箱",
            "treasure_level" to "等級",
            "treasure_level_progress" to "距下一等級",
            "treasure_collection" to "寶物收藏",
            "treasure_locked" to "已鎖定",
            "treasure_set_featured" to "設為代表寶物",
            "treasure_is_featured" to "正在展示中 ✨",
            "treasure_hint_points" to "還需 %dP 可獲得下一個寶物。",
            "treasure_featured_section" to "代表寶物展示台",
            "treasure_achieved" to "已獲得！",
            "treasure_not_yet" to "這個寶物尚未解鎖。",
            "treasure_name_0" to "黃金鑰匙",
            "treasure_name_1" to "紅寶石戒指",
            "treasure_name_2" to "冒險地圖",
            "treasure_name_3" to "黃金甕",
            "treasure_name_4" to "勇者之劍",
            "treasure_name_5" to "守護之盾",
            "treasure_name_6" to "神秘寶石",
            "treasure_name_7" to "閃耀王冠",
            "treasure_name_8" to "傳說星石",
            "treasure_desc_0" to "紀念踏出第一步冒險勇氣的寶物。",
            "treasure_desc_1" to "透過持續努力所獲得的珍貴寶物。",
            "treasure_desc_2" to "紀念挑戰多種運算探索精神的寶物。",
            "treasure_desc_3" to "裝滿無盡努力與投入的寶物。",
            "treasure_desc_4" to "克服困難挑戰的勇氣象徵。",
            "treasure_desc_5" to "堅持不懈解題的耐心象徵。",
            "treasure_desc_6" to "紀念多次獲得三星所展現專注力的寶物。",
            "treasure_desc_7" to "展現成為數學之王實力的最高寶物。",
            "treasure_desc_8" to "完成所有挑戰的傳說寶物。",
            "treasure_praise_0" to "你堅持到了最後！真是了不起的開始！",
            "treasure_praise_1" to "你沒有放棄，繼續挑戰下去！",
            "treasure_praise_2" to "難題也不放棄，繼續挑戰下去！",
            "treasure_praise_3" to "你努力累積的成果正在閃閃發光！",
            "treasure_praise_4" to "不怕困難數學的真正勇者！",
            "treasure_praise_5" to "一步一步累積的實力成了堅固的盾牌！",
            "treasure_praise_6" to "你收集的星星成了美好的寶物！",
            "treasure_praise_7" to "太厲害了！你正邁向數學之王的路上！",
            "treasure_praise_8" to "完成所有挑戰的真正數學英雄！",
            // ── Shop ──
            "shop_title" to "裝扮商店",
            "shop_coins" to "🪙 %d 星幣",
            "shop_tab_accessory" to "裝扮",
            "shop_tab_effect" to "效果",
            "shop_tab_deco" to "裝飾",
            "shop_buy" to "購買",
            "shop_owned" to "已擁有",
            "shop_equip" to "裝備",
            "shop_equipped" to "已裝備",
            "shop_not_enough" to "星幣不足",
            "shop_cancel" to "取消",
            "shop_confirm_buy_title" to "確認購買？",
            "shop_confirm_buy_cost" to "將使用 🪙 %d 星幣。",
            "shop_bought_title" to "購買成功！",
            "shop_equip_now_question" to "立即裝備？",
            "shop_later" to "稍後",
            "item_crown" to "王冠",
            "item_hat" to "帽子",
            "item_glasses" to "眼鏡",
            "item_ribbon" to "緞帶",
            "item_star" to "星星",
            "item_party" to "派對效果",
            "item_sparkle" to "閃亮",
            "item_balloon" to "氣球",
            "item_rainbow" to "彩虹",
            "item_flowers" to "花朵",
            "item_castle" to "城堡",
            "shop_tab_head" to "頭部裝飾",
            "shop_tab_badge" to "徽章",
            "shop_tab_bg" to "背景",
            "portrait_title" to "夥伴裝扮",
            "portrait_no_items" to "尚未擁有任何物品",
            "nav_character" to "夥伴",
            "item_medal" to "獎牌",
            "item_diamond" to "鑽石",
            "item_fire" to "火焰",
            "item_shine" to "閃亮",
            "item_night" to "夜空",
            "item_ocean" to "海洋",
            "item_spring" to "春天",
            "item_flower" to "花朵"
        ),
        AppLanguage.CHINESE_SIMPLIFIED to mapOf(
            "reset_records" to "重置记录",
            "start" to "开始",
            "best_record" to "最佳记录",
            "time_format" to "%.2f秒",
            "light" to "浅色",
            "dark" to "深色",
            "reset_confirm_title" to "确定要重置记录吗？",
            "reset" to "重置",
            "cancel" to "取消",
            "reset_confirm_message" to "最佳记录将被删除。",
            "countdown_go" to "开始！",
            "complete" to "完成！",
            "new_record_title" to "破纪录了！🎉",
            "new_record_message" to "你完成了全部10题\n并创下新纪录。恭喜！",
            "well_done" to "辛苦了",
            "best_record_format" to "最佳记录 %s",
            "to_main" to "返回主页",
            "quit_confirm" to "要结束游戏吗？",
            "no" to "否",
            "yes" to "是",
            "confirm" to "确认",
            "language" to "语言",
            "level_easy" to "简单",
            "level_normal" to "普通",
            "help_title" to "难度说明",
            "help_easy_desc" to "• 左侧数字：0~99\n• 右侧数字：0~10\n• 减法时结果不为负数",
            "help_normal_desc" to "• 左侧数字：0~99\n• 右侧数字：0~99\n• 加法和减法（可为负数）",
            // ── New strings for stage UX ──
            "resume" to "继续",
            "new_start" to "选择运算",
            "select_operation" to "选择运算",
            "overall_progress" to "整体进度",
            "locked" to "已锁定",
            "stage_map_title" to "选择关卡",
            "reset_progress" to "重置进度",
            "reset_progress_confirm_title" to "确定要重置进度吗？",
            "reset_progress_confirm_message" to "所有关卡记录将被删除。",
            "stage_num_format" to "第%d关",
            "resume_hint" to "%s 第%d关",
            "problem_progress" to "%d / 10",
            "result_title_3star" to "太棒了！",
            "result_title_2star" to "做得好！",
            "result_title_1star" to "完成了！",
            "correct_format" to "答对：%d / 10",
            "avg_time_format" to "平均 %.1f秒",
            "retry" to "再试一次",
            "next_stage" to "下一关",
            "to_stage_map" to "关卡地图",
            "star_cond_3" to "⭐⭐⭐  满分 + 平均≤6秒",
            "star_cond_2" to "⭐⭐  答对8题以上",
            "star_cond_1" to "⭐  完成全部题目",
            "points_earned" to "获得 %d 星点数！",
            "hearts_display" to "❤️ %d / %d",
            "next_heart_timer" to "+1 %02d:%02d",
            "total_points_format" to "⭐ %d 星点数",
            "avg_label" to "平均",
            "stage_confirm_title" to "开始关卡",
            "stage_confirm_message" to "要开始%s吗？",
            "stage_start" to "开始",
            "multiple_choice" to "选择题",
            "fill_in" to "填空题",
            "to_home" to "回主页",
            // ── Onboarding & Character ──
            "onboarding_title" to "开始赛兔的运算冒险！",
            "onboarding_desc" to "解开有趣的题目\n与冒险伙伴一起收集星星吧！",
            "onboarding_start" to "🚀 开始冒险",
            "select_character" to "选择今天的冒险伙伴",
            "character_confirm" to "与伙伴一起出发！🎉",
            "char_bear" to "小熊",
            "char_rabbit" to "兔子",
            "char_fox" to "狐狸",
            "char_owl" to "猫头鹰",
            "char_cat" to "猫咪",
            "char_dog" to "小狗",
            // ── Daily Quest ──
            "quest_title" to "今日任务",
            "quest_continue" to "继续 🚀",
            "quest_completed_title" to "今日任务完成！",
            "quest_completed_sub" to "太棒了！今天的冒险完成了！",
            "quest_desc_progress" to "%s 第%d关 挑战",
            "quest_desc_review" to "%s 第%d关 复习",
            "quest_desc_new" to "%s 初次尝试",
            "quest_problems" to "%d题",
            "quest_progress_start" to "开始吧！🎯",
            "quest_progress_remaining" to "再 %d 题就完成！💪",
            "quest_buddy_hint" to "今天一起加油！💪",
            // ── Bottom Nav ──
            "nav_home" to "首页",
            "nav_report" to "探险记录",
            "nav_treasure" to "星宝箱",
            // ── Learning Report ──
            "report_title" to "探险记录",
            "report_solved" to "完成题目",
            "report_accuracy" to "正确率",
            "report_streak" to "连续学习",
            "report_streak_unit" to "天",
            "report_weekly" to "本周学习记录",
            "report_badges" to "获得徽章",
            "report_day_mon" to "一",
            "report_day_tue" to "二",
            "report_day_wed" to "三",
            "report_day_thu" to "四",
            "report_day_fri" to "五",
            "report_day_sat" to "六",
            "report_day_sun" to "日",
            // ── Badges ──
            "badge_first_step" to "第一步",
            "badge_first_step_desc" to "完成第一个关卡",
            "badge_speed_demon" to "闪电手",
            "badge_speed_demon_desc" to "获得3颗星",
            "badge_perfectionist" to "完美主义者",
            "badge_perfectionist_desc" to "10次获得3颗星",
            "badge_math_master" to "数学达人",
            "badge_math_master_desc" to "完成所有关卡",
            "badge_consistent" to "坚持不懈",
            "badge_consistent_desc" to "连续7天学习",
            "badge_explorer" to "探险家",
            "badge_explorer_desc" to "挑战所有运算",
            // ── Parent Settings ──
            "parent_settings_title" to "设置",
            "parent_notifications" to "通知设置",
            "parent_study_notification" to "学习提醒",
            "parent_achievement_notification" to "成就通知",
            "parent_study_management" to "学习管理",
            "parent_time_limit" to "时间限制",
            "parent_daily_goal" to "每日学习目标（分钟）",
            "parent_display" to "显示",
            "parent_data" to "数据",
            "parent_account" to "账号",
            "parent_logout" to "登出",
            // ── Treasure Chest ──
            "treasure_title" to "星宝箱",
            "treasure_level" to "等级",
            "treasure_level_progress" to "距下一等级",
            "treasure_collection" to "宝物收藏",
            "treasure_locked" to "已锁定",
            "treasure_set_featured" to "设为代表宝物",
            "treasure_is_featured" to "正在展示中 ✨",
            "treasure_hint_points" to "还需 %dP 可获得下一个宝物。",
            "treasure_featured_section" to "代表宝物展示台",
            "treasure_achieved" to "已获得！",
            "treasure_not_yet" to "这个宝物尚未解锁。",
            "treasure_name_0" to "黄金钥匙",
            "treasure_name_1" to "红宝石戒指",
            "treasure_name_2" to "冒险地图",
            "treasure_name_3" to "黄金罐",
            "treasure_name_4" to "勇者之剑",
            "treasure_name_5" to "守护之盾",
            "treasure_name_6" to "神秘宝石",
            "treasure_name_7" to "闪耀王冠",
            "treasure_name_8" to "传说星石",
            "treasure_desc_0" to "纪念踏出第一步冒险勇气的宝物。",
            "treasure_desc_1" to "通过持续努力所获得的珍贵宝物。",
            "treasure_desc_2" to "纪念挑战多种运算探索精神的宝物。",
            "treasure_desc_3" to "装满无尽努力与投入的宝物。",
            "treasure_desc_4" to "克服困难挑战的勇气象征。",
            "treasure_desc_5" to "坚持不懈解题的耐心象征。",
            "treasure_desc_6" to "纪念多次获得三星所展现专注力的宝物。",
            "treasure_desc_7" to "展现成为数学之王实力的最高宝物。",
            "treasure_desc_8" to "完成所有挑战的传说宝物。",
            "treasure_praise_0" to "你坚持到了最后！真是了不起的开始！",
            "treasure_praise_1" to "你没有放弃，继续挑战下去！",
            "treasure_praise_2" to "难题也不放弃，继续挑战下去！",
            "treasure_praise_3" to "你努力积累的成果正在闪闪发光！",
            "treasure_praise_4" to "不怕困难数学的真正勇者！",
            "treasure_praise_5" to "一步一步积累的实力成了坚固的盾牌！",
            "treasure_praise_6" to "你收集的星星成了美好的宝物！",
            "treasure_praise_7" to "太厉害了！你正迈向数学之王的路上！",
            "treasure_praise_8" to "完成所有挑战的真正数学英雄！",
            // ── Shop ──
            "shop_title" to "装扮商店",
            "shop_coins" to "🪙 %d 星币",
            "shop_tab_accessory" to "装扮",
            "shop_tab_effect" to "效果",
            "shop_tab_deco" to "装饰",
            "shop_buy" to "购买",
            "shop_owned" to "已拥有",
            "shop_equip" to "装备",
            "shop_equipped" to "已装备",
            "shop_not_enough" to "星币不足",
            "shop_cancel" to "取消",
            "shop_confirm_buy_title" to "确认购买？",
            "shop_confirm_buy_cost" to "将使用 🪙 %d 星币。",
            "shop_bought_title" to "购买成功！",
            "shop_equip_now_question" to "立即装备？",
            "shop_later" to "稍后",
            "item_crown" to "王冠",
            "item_hat" to "帽子",
            "item_glasses" to "眼镜",
            "item_ribbon" to "丝带",
            "item_star" to "星星",
            "item_party" to "派对效果",
            "item_sparkle" to "闪闪发光",
            "item_balloon" to "气球",
            "item_rainbow" to "彩虹",
            "item_flowers" to "花朵",
            "item_castle" to "城堡",
            "shop_tab_head" to "头部装饰",
            "shop_tab_badge" to "徽章",
            "shop_tab_bg" to "背景",
            "portrait_title" to "伙伴装扮",
            "portrait_no_items" to "尚未拥有任何物品",
            "nav_character" to "伙伴",
            "item_medal" to "奖牌",
            "item_diamond" to "钻石",
            "item_fire" to "火焰",
            "item_shine" to "闪亮",
            "item_night" to "夜空",
            "item_ocean" to "海洋",
            "item_spring" to "春天",
            "item_flower" to "花朵"
        ),
        AppLanguage.JAPANESE to mapOf(
            "reset_records" to "記録をリセット",
            "start" to "スタート",
            "best_record" to "最高記録",
            "time_format" to "%.2f秒",
            "light" to "ライト",
            "dark" to "ダーク",
            "reset_confirm_title" to "記録をリセットしますか？",
            "reset" to "リセット",
            "cancel" to "キャンセル",
            "reset_confirm_message" to "最高記録が削除されます。",
            "countdown_go" to "スタート！",
            "complete" to "完了！",
            "new_record_title" to "新記録達成！🎉",
            "new_record_message" to "10問すべて解いて\n新記録を達成しました。おめでとう！",
            "well_done" to "お疲れ様でした",
            "best_record_format" to "最高記録 %s",
            "to_main" to "メインへ",
            "quit_confirm" to "ゲームを終了しますか？",
            "no" to "いいえ",
            "yes" to "はい",
            "confirm" to "確認",
            "language" to "言語",
            "level_easy" to "かんたん",
            "level_normal" to "ふつう",
            "help_title" to "レベル説明",
            "help_easy_desc" to "• 左の数字：0~99\n• 右の数字：0~10\n• 引き算は結果がマイナスにならない",
            "help_normal_desc" to "• 左の数字：0~99\n• 右の数字：0~99\n• 足し算と引き算（マイナス可）",
            // ── New strings for stage UX ──
            "resume" to "続ける",
            "new_start" to "演算を選ぶ",
            "select_operation" to "演算を選択",
            "overall_progress" to "全体の進捗",
            "locked" to "ロック中",
            "stage_map_title" to "ステージ選択",
            "reset_progress" to "進捗をリセット",
            "reset_progress_confirm_title" to "進捗をリセットしますか？",
            "reset_progress_confirm_message" to "すべてのステージ記録が削除されます。",
            "stage_num_format" to "第%dステージ",
            "resume_hint" to "%s 第%dステージ",
            "problem_progress" to "%d / 10",
            "result_title_3star" to "完璧！",
            "result_title_2star" to "よくできました！",
            "result_title_1star" to "クリア！",
            "correct_format" to "正解: %d / 10",
            "avg_time_format" to "平均 %.1f秒",
            "retry" to "もう一度",
            "next_stage" to "次のステージへ",
            "to_stage_map" to "ステージマップ",
            "star_cond_3" to "⭐⭐⭐  満点 + 平均6秒以内",
            "star_cond_2" to "⭐⭐  8問以上正解",
            "star_cond_1" to "⭐  全問クリア",
            "points_earned" to "%d 星ポイント獲得！",
            "hearts_display" to "❤️ %d / %d",
            "next_heart_timer" to "+1 %02d:%02d",
            "total_points_format" to "⭐ %d 星ポイント",
            "avg_label" to "平均",
            "stage_confirm_title" to "ステージ開始",
            "stage_confirm_message" to "%sを始めますか？",
            "stage_start" to "始める",
            "multiple_choice" to "選択式",
            "fill_in" to "記述式",
            "to_home" to "ホームへ",
            // ── Onboarding & Character ──
            "onboarding_title" to "セムトッキと計算冒険を始めよう！",
            "onboarding_desc" to "楽しい問題を解いて\n冒険仲間と星を集めよう！",
            "onboarding_start" to "🚀 冒険スタート",
            "select_character" to "今日の冒険仲間を選ぼう",
            "character_confirm" to "仲間と一緒に行こう！🎉",
            "char_bear" to "クマ",
            "char_rabbit" to "ウサギ",
            "char_fox" to "キツネ",
            "char_owl" to "フクロウ",
            "char_cat" to "ネコ",
            "char_dog" to "イヌ",
            // ── Daily Quest ──
            "quest_title" to "今日のクエスト",
            "quest_continue" to "続ける 🚀",
            "quest_completed_title" to "今日のクエスト達成！",
            "quest_completed_sub" to "すごい！今日の冒険が完了したよ！",
            "quest_desc_progress" to "%s 第%dステージ 挑戦",
            "quest_desc_review" to "%s 第%dステージ 復習",
            "quest_desc_new" to "%s はじめての挑戦",
            "quest_problems" to "%d問",
            "quest_progress_start" to "始めよう！🎯",
            "quest_progress_remaining" to "あと %d 問！💪",
            "quest_buddy_hint" to "今日もいっしょに！💪",
            // ── Bottom Nav ──
            "nav_home" to "ホーム",
            "nav_report" to "冒険記録",
            "nav_treasure" to "星宝箱",
            // ── Learning Report ──
            "report_title" to "冒険記録",
            "report_solved" to "解いた問題",
            "report_accuracy" to "正解率",
            "report_streak" to "連続学習",
            "report_streak_unit" to "日",
            "report_weekly" to "週間学習記録",
            "report_badges" to "獲得バッジ",
            "report_day_mon" to "月",
            "report_day_tue" to "火",
            "report_day_wed" to "水",
            "report_day_thu" to "木",
            "report_day_fri" to "金",
            "report_day_sat" to "土",
            "report_day_sun" to "日",
            // ── Badges ──
            "badge_first_step" to "はじめの一歩",
            "badge_first_step_desc" to "最初のステージをクリア",
            "badge_speed_demon" to "スピードスター",
            "badge_speed_demon_desc" to "3つ星を獲得",
            "badge_perfectionist" to "パーフェクト",
            "badge_perfectionist_desc" to "3つ星を10回達成",
            "badge_math_master" to "算数マスター",
            "badge_math_master_desc" to "全ステージクリア",
            "badge_consistent" to "継続力",
            "badge_consistent_desc" to "7日連続学習",
            "badge_explorer" to "探検家",
            "badge_explorer_desc" to "全演算に挑戦",
            // ── Parent Settings ──
            "parent_settings_title" to "設定",
            "parent_notifications" to "通知設定",
            "parent_study_notification" to "学習リマインダー",
            "parent_achievement_notification" to "実績通知",
            "parent_study_management" to "学習管理",
            "parent_time_limit" to "時間制限",
            "parent_daily_goal" to "1日の学習目標（分）",
            "parent_display" to "表示",
            "parent_data" to "データ",
            "parent_account" to "アカウント",
            "parent_logout" to "ログアウト",
            // ── Treasure Chest ──
            "treasure_title" to "星宝箱",
            "treasure_level" to "レベル",
            "treasure_level_progress" to "次のレベルまで",
            "treasure_collection" to "コレクション",
            "treasure_locked" to "ロック中",
            "treasure_set_featured" to "代表の宝物として展示する",
            "treasure_is_featured" to "展示中 ✨",
            "treasure_hint_points" to "次の宝物まであと %dP。",
            "treasure_featured_section" to "代表の宝物展示台",
            "treasure_achieved" to "獲得済み！",
            "treasure_not_yet" to "この宝物はまだロック中です。",
            "treasure_name_0" to "黄金の鍵",
            "treasure_name_1" to "ルビーの指輪",
            "treasure_name_2" to "冒険の地図",
            "treasure_name_3" to "黄金の壺",
            "treasure_name_4" to "勇者の剣",
            "treasure_name_5" to "守護の盾",
            "treasure_name_6" to "神秘の宝石",
            "treasure_name_7" to "輝く王冠",
            "treasure_name_8" to "伝説の星",
            "treasure_desc_0" to "初めての冒険を始めた勇気を称える宝物。",
            "treasure_desc_1" to "コツコツと努力して手に入れた大切な宝物。",
            "treasure_desc_2" to "さまざまな計算に挑んだ探求心を称える宝物。",
            "treasure_desc_3" to "絶えぬ努力と情熱で満たされた宝物。",
            "treasure_desc_4" to "困難な挑戦を乗り越えた勇気の象徴。",
            "treasure_desc_5" to "諦めずに問題を解き続けた忍耐の象徴。",
            "treasure_desc_6" to "何度も三つ星を獲得した集中力を称える宝物。",
            "treasure_desc_7" to "算数の王になる実力を示した最高の宝物。",
            "treasure_desc_8" to "すべての挑戦を完成させた伝説の宝物。",
            "treasure_praise_0" to "最後までやりきったね。素晴らしいスタートだよ！",
            "treasure_praise_1" to "諦めずにチャレンジし続けたね！",
            "treasure_praise_2" to "難しい問題も諦めずに挑戦したね！",
            "treasure_praise_3" to "積み重ねてきた努力が輝いているよ！",
            "treasure_praise_4" to "算数も怖くない、本物の勇者だよ！",
            "treasure_praise_5" to "一歩一歩積み上げた力が盾になったね！",
            "treasure_praise_6" to "集めた星たちが素敵な宝物になったね！",
            "treasure_praise_7" to "すごい！算数の王への道を歩んでいるよ！",
            "treasure_praise_8" to "すべての挑戦を完成させた本物の算数ヒーローだよ！",
            // ── Shop ──
            "shop_title" to "コーデショップ",
            "shop_coins" to "🪙 %d星コイン",
            "shop_tab_accessory" to "コーデ",
            "shop_tab_effect" to "エフェクト",
            "shop_tab_deco" to "デコ",
            "shop_buy" to "購入",
            "shop_owned" to "所持",
            "shop_equip" to "装備",
            "shop_equipped" to "装備中",
            "shop_not_enough" to "星コイン不足",
            "shop_cancel" to "キャンセル",
            "shop_confirm_buy_title" to "購入しますか？",
            "shop_confirm_buy_cost" to "🪙 %d星コインが使われます。",
            "shop_bought_title" to "購入しました！",
            "shop_equip_now_question" to "今すぐ装備しますか？",
            "shop_later" to "あとで",
            "item_crown" to "王冠",
            "item_hat" to "帽子",
            "item_glasses" to "メガネ",
            "item_ribbon" to "リボン",
            "item_star" to "お星様",
            "item_party" to "パーティ",
            "item_sparkle" to "キラキラ",
            "item_balloon" to "バルーン",
            "item_rainbow" to "虹",
            "item_flowers" to "お花",
            "item_castle" to "お城",
            "shop_tab_head" to "頭飾り",
            "shop_tab_badge" to "バッジ",
            "shop_tab_bg" to "背景",
            "portrait_title" to "仲間スタイル",
            "portrait_no_items" to "アイテムなし",
            "nav_character" to "仲間",
            "item_medal" to "メダル",
            "item_diamond" to "ダイヤ",
            "item_fire" to "炎",
            "item_shine" to "シャイン",
            "item_night" to "夜空",
            "item_ocean" to "海",
            "item_spring" to "春",
            "item_flower" to "お花"
        )
    )

    fun string(key: String, lang: AppLanguage, vararg args: Any): String {
        val template = strings[lang]?.get(key) ?: strings[AppLanguage.ENGLISH]!![key] ?: key
        return if (args.isEmpty()) template else kmpFormat(template, *args)
    }
}

/** Multiplatform string formatter — supports %.Nf, %s, and %d specifiers. */
internal fun kmpFormat(template: String, vararg args: Any): String {
    val result = StringBuilder()
    var argIndex = 0
    var i = 0
    while (i < template.length) {
        if (template[i] == '%' && i + 1 < template.length) {
            val rest = template.substring(i + 1)
            val floatMatch = Regex("^\\.(\\d+)f").find(rest)
            val paddedIntMatch = Regex("^0(\\d+)d").find(rest)
            val stringMatch = rest.startsWith("s")
            val intMatch = rest.startsWith("d")
            when {
                floatMatch != null -> {
                    val decimals = floatMatch.groupValues[1].toInt()
                    val value = (args.getOrNull(argIndex++) as? Number)?.toFloat() ?: 0f
                    result.append(formatFloat(value, decimals))
                    i += 1 + floatMatch.value.length
                }
                paddedIntMatch != null -> {
                    val width = paddedIntMatch.groupValues[1].toInt()
                    val value = (args.getOrNull(argIndex++) as? Number)?.toInt() ?: 0
                    result.append(value.toString().padStart(width, '0'))
                    i += 1 + paddedIntMatch.value.length
                }
                stringMatch -> {
                    result.append(args.getOrNull(argIndex++)?.toString() ?: "")
                    i += 2
                }
                intMatch -> {
                    result.append((args.getOrNull(argIndex++) as? Number)?.toInt() ?: 0)
                    i += 2
                }
                else -> {
                    result.append('%')
                    i++
                }
            }
        } else {
            result.append(template[i])
            i++
        }
    }
    return result.toString()
}

private fun formatFloat(value: Float, decimals: Int): String {
    val absValue = if (value < 0f) -value else value
    val sign = if (value < 0f) "-" else ""
    val multiplier = when (decimals) {
        0 -> 1; 1 -> 10; 2 -> 100; 3 -> 1000; else -> 100
    }
    val scaled = (absValue * multiplier + 0.5f).toInt()
    val intPart = scaled / multiplier
    val fracPart = scaled % multiplier
    return if (decimals == 0) "$sign$intPart"
    else "$sign$intPart.${fracPart.toString().padStart(decimals, '0')}"
}
